version: '3.8'

services:
  finvu-aa-service:
    build: .
    container_name: automation-finvu-aa-service
    ports:
      - "${PORT:-3002}:${PORT:-3002}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - automation-network

networks:
  automation-network:
    driver: bridge

